/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Jugador.Fichas;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author jomel
 */
public class Grupal extends javax.swing.JPanel {
    public ArrayList<String> Team1 = new ArrayList();
    public ArrayList<String> Team2 = new ArrayList();
    public ArrayList<String> Team3 = new ArrayList();
     int Cantidad;
    public Grupal() {
        initComponents();
        setComboUsers();
        Team1.add(Inicio.usuario.getNombre());
        setListTeam1();
        setListTeam2();
        setListTeam3();
        Cantidad = 2;
        ComboTeam2.setSelectedIndex(1);
        ComboTeam3.setSelectedIndex(2);
        Equipo3.setVisible(false);
            ComboTeam3.setVisible(false);
            jScrollPane3.setVisible(false);
            txtTeam3.setVisible(false);
            Team.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Equipo 1", "Equipo 2"}));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NumPlayers = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtTeam3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Equipo1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        Equipo2 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        Equipo3 = new javax.swing.JList<>();
        Players = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        Team = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        ComboTeam2 = new javax.swing.JComboBox<>();
        ComboTeam1 = new javax.swing.JComboBox<>();
        ComboTeam3 = new javax.swing.JComboBox<>();
        Add = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Equipo 2:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Cantidad de Jugadores:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 21, 202, -1));

        NumPlayers.setBackground(new java.awt.Color(255, 204, 204));
        NumPlayers.setForeground(new java.awt.Color(0, 0, 0));
        NumPlayers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4", "6", "8" }));
        NumPlayers.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                NumPlayersItemStateChanged(evt);
            }
        });
        add(NumPlayers, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 23, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Equipo 1:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        txtTeam3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTeam3.setForeground(new java.awt.Color(0, 0, 0));
        txtTeam3.setText("Equipo 3:");
        add(txtTeam3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, -1, -1));

        Equipo1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(Equipo1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 107, 64));

        Equipo2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(Equipo2);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 107, 64));

        Equipo3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(Equipo3);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 107, 64));

        Players.setBackground(new java.awt.Color(255, 204, 204));
        Players.setForeground(new java.awt.Color(0, 0, 0));
        Players.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Players.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayersActionPerformed(evt);
            }
        });
        add(Players, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Equipo:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, -1, -1));

        Team.setBackground(new java.awt.Color(255, 204, 204));
        Team.setForeground(new java.awt.Color(0, 0, 0));
        Team.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Equipo 1", "Equipo 2", "Equipo 3" }));
        add(Team, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Jugador:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        ComboTeam2.setBackground(new java.awt.Color(255, 204, 204));
        ComboTeam2.setForeground(new java.awt.Color(0, 0, 0));
        ComboTeam2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rojo", "Azul", "Amarillo" }));
        ComboTeam2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboTeam2ItemStateChanged(evt);
            }
        });
        add(ComboTeam2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, -1));

        ComboTeam1.setBackground(new java.awt.Color(255, 204, 204));
        ComboTeam1.setForeground(new java.awt.Color(0, 0, 0));
        ComboTeam1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rojo", "Azul", "Amarillo" }));
        ComboTeam1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboTeam1ItemStateChanged(evt);
            }
        });
        add(ComboTeam1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        ComboTeam3.setBackground(new java.awt.Color(255, 204, 204));
        ComboTeam3.setForeground(new java.awt.Color(0, 0, 0));
        ComboTeam3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rojo", "Azul", "Amarillo" }));
        ComboTeam3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboTeam3ItemStateChanged(evt);
            }
        });
        add(ComboTeam3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, -1, -1));

        Add.setBackground(new java.awt.Color(51, 0, 0));
        Add.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Add.setForeground(new java.awt.Color(255, 255, 255));
        Add.setText("Añadir");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void PlayersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlayersActionPerformed

    private void NumPlayersItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_NumPlayersItemStateChanged
        // TODO add your handling code here:
        if(NumPlayers.getSelectedIndex() != 2){
            Cantidad = 4;
        }else{
            Cantidad = 2;
        }
        
        if(NumPlayers.getSelectedIndex() == 1){
            Equipo3.setVisible(true);
            ComboTeam3.setVisible(true);
            jScrollPane3.setVisible(true);
            txtTeam3.setVisible(true);
            Team.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Equipo 1", "Equipo 2", "Equipo 3" }));
        }else{
            Team3 = new ArrayList();
            Equipo3.setVisible(false);
            ComboTeam3.setVisible(false);
            jScrollPane3.setVisible(false);
            txtTeam3.setVisible(false);
            Team.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Equipo 1", "Equipo 2"}));
        }
    }//GEN-LAST:event_NumPlayersItemStateChanged

    private void ComboTeam1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboTeam1ItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ComboTeam1ItemStateChanged

    private void ComboTeam2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboTeam2ItemStateChanged
        // TODO add your handling code here:
        //Aui es Team2
        
    }//GEN-LAST:event_ComboTeam2ItemStateChanged

    private void ComboTeam3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboTeam3ItemStateChanged
        // TODO add your handling code here:
       
    }//GEN-LAST:event_ComboTeam3ItemStateChanged

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
        String user = Players.getSelectedItem().toString();
        if(!user.equals(Inicio.usuario.getNombre())){
            if(!Team1.contains(user ) && !Team2.contains(user) && !Team3.contains(user)){
            switch(Team.getSelectedIndex()){
                case 0:
                    if(Team1.size() < Cantidad){
                        Team1.add(user);
                        setListTeam1();
                    }
                    break;
                case 1:
                    if(Team2.size() < Cantidad){
                        Team2.add(user);
                        setListTeam2();
                    }
                    break;
                case 2:
                    if(Team3.size() < Cantidad){
                        Team3.add(user);
                        setListTeam3();
                    }
                    break;
                }
            }else{
                JOptionPane.showMessageDialog(null,"ERROR: Ese jugador ya esta agregado a un equipo.");
            }
        }else{
            JOptionPane.showMessageDialog(null,"ERROR: Ese jugador ya esta agregado a un equipo.");
        }
    }//GEN-LAST:event_AddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JComboBox<String> ComboTeam1;
    private javax.swing.JComboBox<String> ComboTeam2;
    private javax.swing.JComboBox<String> ComboTeam3;
    private javax.swing.JList<String> Equipo1;
    private javax.swing.JList<String> Equipo2;
    private javax.swing.JList<String> Equipo3;
    private javax.swing.JComboBox<String> NumPlayers;
    private javax.swing.JComboBox<String> Players;
    private javax.swing.JComboBox<String> Team;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel txtTeam3;
    // End of variables declaration//GEN-END:variables
    
    void setComboUsers(){
        String[] usuarios = new String[Inicio.ManagerAcc.size()];
        int contador = 0;
        for(Usuario.Usuario usuario: Inicio.ManagerAcc.getUsers()){
            usuarios[contador] = usuario.getNombre();
            contador++;
        }
        
        Players.setModel(new javax.swing.DefaultComboBoxModel<>(usuarios));
    }
    
    void setListTeam1(){
        Equipo1.setModel(new javax.swing.AbstractListModel<String>(){
            String[] send = Team1.toArray(new String[Team1.size()]);
            String[] strings = send;
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
    }
    
    void setListTeam2(){
        Equipo2.setModel(new javax.swing.AbstractListModel<String>(){
            String[] send = Team2.toArray(new String[Team2.size()]);
            String[] strings = send;
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
    }
    
    void setListTeam3(){
        Equipo3.setModel(new javax.swing.AbstractListModel<String>(){
            String[] send = Team3.toArray(new String[Team3.size()]);
            String[] strings = send;
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
    }
    
    boolean diffTokens(){
        int one = ComboTeam1.getSelectedIndex();
        int two = ComboTeam2.getSelectedIndex();
        int three = ComboTeam3.getSelectedIndex();
        
        if(ComboTeam3.isVisible() && (one == two || one == three || two == three) || 
                !ComboTeam3.isVisible() && (one == two)){
            JOptionPane.showMessageDialog(null, "ERROR: Las fichas son iguales para un equipo.");
            return false;
        }
        return true;
    }
    
    boolean diffTeams(){
        if(ComboTeam3.isVisible()){
            return Team1.size() == 2 && Team2.size() == 2 && Team3.size() == 2;
        }else if(Cantidad == 2){
            return Team1.size() == 2 && Team2.size() == 2;
        }else{
            return Team1.size() == 4 && Team2.size() == 4;
        }
    }
    
    ArrayList<String> getTeams(){
        ArrayList<String> listado = new ArrayList();
        listado.addAll(Team1);
        for(String user:Team1){
            Usuario.Usuario usuario = Inicio.ManagerAcc.searchUser(user);
            switch(ComboTeam1.getSelectedIndex()){
                case 0:
                    usuario.setFicha(Fichas.RED);
                    break;
                case 1:
                    usuario.setFicha(Fichas.BLUE);
                    break;
                case 2:
                    usuario.setFicha(Fichas.YELLOW);
                    break;
            }
        }
        listado.addAll(Team2);
        for(String user:Team2){
            Usuario.Usuario usuario = Inicio.ManagerAcc.searchUser(user);
            switch(ComboTeam2.getSelectedIndex()){
                case 0:
                    usuario.setFicha(Fichas.RED);
                    break;
                case 1:
                    usuario.setFicha(Fichas.BLUE);
                    break;
                case 2:
                    usuario.setFicha(Fichas.YELLOW);
                    break;
            }
        }
        if(Team3.size() != 0){
            listado.addAll(Team3);
            for(String user:Team3){
            Usuario.Usuario usuario = Inicio.ManagerAcc.searchUser(user);
            switch(ComboTeam3.getSelectedIndex()){
                case 0:
                    usuario.setFicha(Fichas.RED);
                    break;
                case 1:
                    usuario.setFicha(Fichas.BLUE);
                    break;
                case 2:
                    usuario.setFicha(Fichas.YELLOW);
                    break;
            }
        }
        }
        return listado;
    }
}
