/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.io.IOException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javaswingdev.drawer.Drawer;
import javaswingdev.drawer.DrawerController;
import javax.swing.Timer;

/**
 *
 * @author jomel
 */
public class Menu extends javax.swing.JFrame {

    int XMouse;
    int YMouse;
    Timer timer;
    DrawerController Sidebar;
    
    public Menu() {
        initComponents();
        Time();
        timer = new Timer(1000, (ActionEvent e) ->{
            Time();
        });
        Sidebar = Drawer.newDrawer(this).addChild(new SideBar(this)).build();
        timer.start();
        AgregarPanel(new Jugar(this));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SideBar = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        UpperTaskBar = new javax.swing.JPanel();
        BcExit = new javax.swing.JPanel();
        btnExit = new javax.swing.JLabel();
        Time = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Container = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SideBar.setBackground(new java.awt.Color(51, 0, 0));
        SideBar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SideBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SideBarMouseEntered(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("<<<");

        javax.swing.GroupLayout SideBarLayout = new javax.swing.GroupLayout(SideBar);
        SideBar.setLayout(SideBarLayout);
        SideBarLayout.setHorizontalGroup(
            SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        SideBarLayout.setVerticalGroup(
            SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideBarLayout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(225, 225, 225)
                .addComponent(jLabel1)
                .addGap(0, 293, Short.MAX_VALUE))
        );

        jPanel1.add(SideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 60, 560));

        UpperTaskBar.setBackground(new java.awt.Color(51, 0, 0));
        UpperTaskBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                UpperTaskBarMouseDragged(evt);
            }
        });
        UpperTaskBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UpperTaskBarMousePressed(evt);
            }
        });

        BcExit.setBackground(new java.awt.Color(51, 0, 0));
        BcExit.setForeground(new java.awt.Color(204, 204, 204));

        btnExit.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnExit.setText("X");
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnExitMousePressed(evt);
            }
        });

        javax.swing.GroupLayout BcExitLayout = new javax.swing.GroupLayout(BcExit);
        BcExit.setLayout(BcExitLayout);
        BcExitLayout.setHorizontalGroup(
            BcExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BcExitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BcExitLayout.setVerticalGroup(
            BcExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BcExitLayout.createSequentialGroup()
                .addComponent(btnExit)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        Time.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        Time.setForeground(new java.awt.Color(255, 255, 255));
        Time.setText("00:00:00");
        Time.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo_Peque.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout UpperTaskBarLayout = new javax.swing.GroupLayout(UpperTaskBar);
        UpperTaskBar.setLayout(UpperTaskBarLayout);
        UpperTaskBarLayout.setHorizontalGroup(
            UpperTaskBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpperTaskBarLayout.createSequentialGroup()
                .addComponent(BcExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 481, Short.MAX_VALUE)
                .addComponent(Time)
                .addGap(39, 39, 39)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        UpperTaskBarLayout.setVerticalGroup(
            UpperTaskBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BcExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(UpperTaskBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UpperTaskBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Time, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel1.add(UpperTaskBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        Container.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout ContainerLayout = new javax.swing.GroupLayout(Container);
        Container.setLayout(ContainerLayout);
        ContainerLayout.setHorizontalGroup(
            ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );
        ContainerLayout.setVerticalGroup(
            ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        jPanel1.add(Container, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 730, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        // TODO add your handling code here:
        BcExit.setBackground(Color.red);
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        // TODO add your handling code here:
        BcExit.setBackground(new java.awt.Color(51,0,0));
    }//GEN-LAST:event_btnExitMouseExited

    private void btnExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMousePressed
        // TODO add your handling code here:
        
        try {
            Inicio.writeData();
        } catch (Exception ex) {
        } 
        System.exit(0);
    }//GEN-LAST:event_btnExitMousePressed

    private void UpperTaskBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpperTaskBarMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-XMouse, y-YMouse);
    }//GEN-LAST:event_UpperTaskBarMouseDragged

    private void UpperTaskBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpperTaskBarMousePressed
        // TODO add your handling code here:
        XMouse = evt.getX();
        YMouse = evt.getY();

    }//GEN-LAST:event_UpperTaskBarMousePressed

    private void SideBarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SideBarMouseEntered
        // TODO add your handling code here:
        Sidebar.show();
    }//GEN-LAST:event_SideBarMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BcExit;
    private javax.swing.JPanel Container;
    private javax.swing.JPanel SideBar;
    private javax.swing.JLabel Time;
    private javax.swing.JPanel UpperTaskBar;
    private javax.swing.JLabel btnExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
    
    private void Time(){
        Calendar ahora = Calendar.getInstance();
        int hora = ahora.get(Calendar.HOUR_OF_DAY);
        int minuto = ahora.get(Calendar.MINUTE);
        int segundo = ahora.get(Calendar.SECOND);
        
        String txt = "";
        if(hora < 10){
            txt += "0";
        }
        txt += hora + ":";
        
        if(minuto <10){
            txt += "0"; 
        }
        txt += minuto + ":";
        
        if(segundo < 10){
             txt += "0"; 
        }
        txt += segundo;
        Time.setText(txt);
        
    }
    
    public void AgregarPanel(javax.swing.JPanel Panel){
        Panel.setSize(740, 550);
        Panel.setLocation(0, 0);
        Container.removeAll();
        Container.add(Panel);
        Container.revalidate();
        Container.repaint();
    }
}
